//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace botke.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class botkedbEntities2 : DbContext
    {
        public botkedbEntities2()
            : base("name=botkedbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<getEvent_Result> getEvent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEvent_Result>("getEvent");
        }
    
        public virtual ObjectResult<getuser_Result> getuser(string name, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getuser_Result>("getuser", nameParameter, passwordParameter);
        }
    }
}
